### ISSUE TITLE
7.5 minute topos not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BNHM/berkeleymapper#33]
```
turn on "Topos" and zoom way in and then you don't see any data... what is 
going on here.


```

Original issue reported on code.google.com by `jdec...@gmail.com` on 15 Aug 2012 at 8:47

**Comment by jdeck88** [comment]
I'm not sure this is a bug--- google doesn't render any data at certain zoom levels for topos.  however, there should be a way to detect whether data is being sent given raster layers OR perhaps only zoom in a certain amount given the constraints of the back-ground layers?

**Comment by mkoo** [comment]
Can be met with #60
