### ISSUE TITLE
Printing from mapper only prints top 1/3 of page.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BNHM/berkeleymapper#46]
```
This was reported by Dick Moe.
```

Original issue reported on code.google.com by `jdec...@gmail.com` on 22 Sep 2012 at 6:53

**Comment by mkoo** [comment]
Still not printing correctly-- no points appear on basemap, prints over 2 pages, google maps controls are wonky.... could be fixed for big upgrade project
