### ISSUE TITLE
allow import of JSON/ GEOJSON

### ISSUE THREAD

**Issue by mkoo** [BNHM/berkeleymapper#58]
Specifically for displaying range maps for species. We can easily convert shapefiles to JSON which can be shared widely, versioned in repositories, and are very small files. (KMLs are also shareable but the multitude of KML converters leaves a lot of variation on the KML output side).

Here's an example on github:
https://github.com/AmphibiaWeb/range_maps/tree/master/tests

which renders nicely in Github:
https://github.com/AmphibiaWeb/range_maps/blob/master/tests/Ansonia_thinthinae.json
(it also renders different versions as diffs)

John says 'should not be a problem'!

**Comment by jdeck88** [comment]
This has been implemented.... it was awhile ago, but just getting to this.
