### ISSUE TITLE
new vectors

### ISSUE THREAD

**Issue by mkoo** [BNHM/berkeleymapper#60]
Deck will create a new public repo just for vector directory: https://github.com/BNHM/spatial-layers

Requested list:
- [ ] Watershed -HUC for North America 
- [ ] CPAD or equivalent for Protected Area (and may also be available as webservices)
- [ ] ecoregion for CA (California-based one for CCH); State 
- [ ] ecoregion for world (for AW and Arctos, WWF?)
- [ ] Geology for CA (from State and we may have to dissolve)
- [x] USGS topoquads (7.5 MInute) (shapefile also on my desktop) webservice is probably available
- [ ] CA counties (already exists)

**Comment by mkoo** [comment]
Michael B. requests some cultural layers (eg. Kroeber)

**Comment by PatHolroyd** [comment]
Pat Holroyd suggests looking to GPlates for geology layers for North America <http://portal.gplates.org/static/html/welcome.html>

**Comment by mkoo** [comment]
Footprints for NRS, RECs, maybe UC field stations.

**Comment by mkoo** [comment]
I'll take the first pass at gathering these datasets, first as shapefiles then convert to JSON and/or KML

**Comment by mkoo** [comment]
Separate directories for JSON and KML? Which format retains metadata best or attributes?

**Comment by jdeck88** [comment]
i think kml/kmz would be better at storing attributes in the file, using comments , however, we could put a README.md in each directory to display what files we have and where got them.   I'm certain about having separate directories or no. Since each layer is represented by a single file maybe easier to just put them all under "data"

**Comment by mkoo** [comment]
Update: @jdeck88  I think we dont have enough datasets yet to worry about separate dir and readme's for each one so I started a table on the main Readme and will list the layers in /data/
so far:
- USGS 7.5 topoquads for CONUS
- HUC's need some processing first; apparently too many vertices breaks KMZs
- ecoregions coming....
