### ISSUE TITLE
vector logo?

### ISSUE THREAD

**Issue by mkoo** [BNHM/berkeleymapper#64]
Does one exist? I want to get a standardized button/icon for berkeleymapper links, needless to say, should be scalable.

If it doesnt exist, let's make one!

**Comment by jdeck88** [comment]
a vector logo?
we do have this one raster one:
http://berkeleymapper.berkeley.edu/img/bm_logo.gif
this is scalable.

**Comment by mkoo** [comment]
new logo in place so closing
