### ISSUE TITLE
Can we get accurate National Park property boundaries?

### ISSUE THREAD

**Issue by DerekSikes** [BNHM/berkeleymapper#76]
My tech just wrote "I'm worried about the accuracy of Berkley Mapper's NPS overlays : I was surprised to see Shishmaref wasn't covered (since I'd been under the impression it was within BELA) - confirmed it IS within the park (https://www.nps.gov/bela/planyourvisit/shishmaref.htm), but it's clearly not on here... "
![image](https://user-images.githubusercontent.com/9099827/36809991-0bb33c4c-1c76-11e8-807e-e82bffb930e9.png)

**Comment by jdeck88** [comment]
Berkeleymapper doesn't have control over boundaries that appear on the base layers, which are generated by Google. I'm sure that they don't guarantee accuracy of these but that would be receptive to improving the map base-layer.... I think you could start here:

https://support.google.com/maps/answer/3094088?co=GENIE.Platform%3DDesktop&hl=en

Closing this issue as not directly a Berkeleymapper issue
